### ISSUE TITLE
한/영키 입력할 때 레이블 "... as hanja key"

### ISSUE THREAD

**Issue by changwoo** [choehwanjin/ibus-hangul#36]
한/영키 입력에 한자키 입력창을 재활용하면서 생각하지 못했던 부분이네요.

https://github.com/choehwanjin/ibus-hangul/blob/master/setup/keycapturedialog.py#L15

해결 방법은 간단해도 여러가지 방법이 있을테니 환진님 결정에 맡깁니다.

**Comment by choehwanjin** [comment]
수정하였습니다.

https://github.com/choehwanjin/ibus-hangul/commit/f48efa5c099f35e127971a9b0abf49ee5a2cd5d5
