### ISSUE TITLE
ibus-engine-hangul dumps core without ibus connection

### ISSUE THREAD

**Issue by KazuhikoMaekawa** [choehwanjin/ibus-hangul#41]
ibus-engine-hangle dumps core when no running ibus-daemon.
This is minor case and low priority issue, but binaries should not dump core by execution.

Steps to reproduce:
  - login using ssh from other host
  - execute /usr/libexec/ibus-engine-hangul (on Fedora)
  Dumps core.

Having ibus_bus_is_connected() check in main.c could solve the issue.

**Comment by choehwanjin** [comment]
Thanks for reporting.
I will check that.

**Comment by choehwanjin** [comment]
I've fixed this issue.

https://github.com/choehwanjin/ibus-hangul/commit/41eb8daf87377951459f1c951ca130cc83fbc32d
